### ISSUE TITLE
Unable to link device - Unexpected response: HTTP 409

### ISSUE THREAD

**Issue by Longpiggy** [boxdot/gurk-rs#313] opened 2024-09-23 03:50 UTC
Getting the title error when trying to link a new device to my account.

Version 0.5.2-dev from AUR.
Kernel: Linux 6.10.10-arch1-1
DE: KDE Plasma 6.1.5
rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1)

```2024-09-23T03:48:02.712426Z  WARN libsignal_service_hyper::websocket: Websocket closing: Some(CloseFrame { code: Normal, reason: "Closed" })
2024-09-23T03:48:02.712469Z ERROR libsignal_service::websocket: SignalWebSocket: Websocket error: end of web request stream; socket closing
2024-09-23T03:48:03.378564Z ERROR put_json{service=Service path="/v1/devices/link" additional_headers=[] credentials_override=Identified(HttpAuth { username: "+redacted" })}:request{method=PUT endpoint=Service additional_headers=[] credentials_override=Identified(HttpAuth { username: "+redacted" }) path=/v1/devices/link}: libsignal_service_hyper::push_service: Failed to decode HTTP 409 response: Error decoding JSON response: missing field missingDevices at line 1 column 42```

**Comment by ephemer4l** [comment] 2024-09-24 04:56
Same issue here. And my device was already linked. I'm running Gentoo musl with rustc 1.80.1 (3f5fd8dd4 2024-08-06) (gentoo).

**Comment by ephemer4l** [comment] 2024-09-24 10:14
I can confirm that the issue is fixed by #314.

**Comment by tx46** [comment] 2024-09-26 03:34
can you publish a buld of this so i can use it?

**Comment by ephemer4l** [comment] 2024-09-26 06:48
> can you publish a buld of this so i can use it?

I have installed it simply by 

```
cargo install --git https://github.com/boxdot/gurk-rs --branch bump-presage-09-24 gurk
```

Maybe you can try the same? I would send the build myself, but I don't think mine would work on your device (because of musl).

**Comment by tealeg** [comment] 2024-10-12 08:12
Same on OpenBSD 7.6.

**Comment by tealeg** [comment] 2024-10-12 08:36
Also confirm that the fix above (#314) gets me past this problem on OpenBSD 7.6

**Closed** 2024-10-17 16:29 UTC

**Comment by pconstr** [comment] 2025-01-25 08:09
getting this error with v0.6.1 (binary from tarball) on macos 15.1.1, Apple M2, when trying to link device

```
Error: failed to provision device: Service error: Unexpected response: HTTP 409

Caused by:
    0: Service error: Unexpected response: HTTP 409
    1: Unexpected response: HTTP 409
```

**Comment by pconstr** [comment] 2025-01-25 08:24
Same error on my Linux box (xbuntu 22.04, AMD64) also running v0.6.1 binary from tarball.

**Comment by pconstr** [comment] 2025-01-25 08:38
Also same error on that Linux box when installing with cargo (`cargo install --git https://github.com/boxdot/gurk-rs gurk`)

**Comment by gferon** [comment] 2025-01-31 13:14
This was fixes yesterday in the upstream library used by `gurk` (https://github.com/whisperfish/presage/commit/4377bdbfc7a94fcbf349cde7ceff9616c43f0830)
